packages:
  - apps/*
  - packages/*
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
peerDependencyRules:
  allowedVersions:
    vite: "0.3.0"
allowBuilds:
  electron: true
  esbuild: true
  msgpackr-extract: false
patchedDependencies:
  drizzle-orm@1.0.0-rc.4: patches/drizzle-orm@1.0.0-rc.4.patch
